format = """
$directory$git_branch$git_status
$character
"""

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_status]
staged = "[+](bold green)"
modified = "[!](bold yellow)"
untracked = "[?](bold blue)"

ahead = "[⇡](bold cyan)"
behind = "[⇣](bold red)"
diverged = "[⇕](bold magenta)"

conflicted = "[✖](bold red)"
deleted = "[✘](bold red)"
renamed = "[»](bold purple)"
stashed = "[≡](bold white)"

[character]
success_symbol = "[❯](bold green) "
error_symbol   = "[❯](bold red) "

[package]
disabled = true

[rust]
disabled = true

[gcloud]
disabled = true

[cmd_duration]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

